language: elixir
elixir:
- 1.3.2
before_install:
- mix local.hex --force
- mix local.rebar --force
- mix do deps.get, deps.compile
script:
- mix test
env:
- TWITTER_CONSUMER_KEY=abc TWITTER_CONSUMER_SECRET=abc
deploy:
  provider: heroku
  app: delete-your-tweets
  api_key:
    secure: kav5d0/b6irUQ6MKiEv7M8EcBOy1TQChGB7+etFm9C5WoMjCNTXoULPdb/szrfuNSqkA/hkuipzgEp57iAXALf8oMFc0LXwnl/qKnyXqErSBN4pIQtlBlMn8QRrVBlO8ifmAQ9FuXpj33i8QMf0eqlIH7306eO3Y8NrEUEUbWCkYUBrELozOfgg86JYcNtM2/5FtxpT0+XlnUv/jS7/FRqMQoC/BG+DPDy9HKvViwEbSSPVJ6Ldggzb/s6UtZZpLsamil+0LQaKGdT7fi21YW5Xci5pxFEQteKtqINmLlD1u+B1M/tObmIkPLt+pgFq7Go3JD+rvhSaDiJrLIrFfFkkmLEUTXAgZ9bGh50OBZzXsicEJK5WwKgI/M7Wi/cQWX86iuv/DmxSa+PzZjArC6YkcWDGPZhrirGAWvXdiORXb4FWVY1+G2K7whbJvN3kyuCb4NQafUS0IO42EgT/1kPI3cQ3KOYx6TVmpCWpsjvpd36BiGXgGY0WtAbFT7q/RHmo+u1b5YQrv0eBtaqIHPPseUIJ5sdcXI3ydnf3FWke4cRp+AvrIgJB8ZGa9+ynDp26zy8pROdq9k7ABjOCx4yxfP84jXLex8pPpl4WeHgOKdrjl5eCtWGHbyQ7gODvMOPhWC165ia3FR1XK+htmHYerbUyq88PTh8/j8Bi/BeY=
