language: elixir
elixir:
- 1.3.2
before_install:
- mix local.hex --force
- mix local.rebar --force
- mix do deps.get, deps.compile
script:
- mix test
env:
- TWITTER_CONSUMER_KEY=abc TWITTER_CONSUMER_SECRET=abc
deploy:
  provider: heroku
  app: delete-your-tweets
  api_key:
    secure: ujAOmO+PxxoFIWH5rBEH6ka99hvC12BRz/a5sLhQVjh/czbJNWw2+3WrR8QH+tie2xUBe1OIc75JJWRfWLvR7LfeyaOzJeRiJOPb8c2GcEUop1Kx1XRTxteGbjuXtkQobmYLeU7VVEN1GNN9IX8hTYJJnuIle336U/T6fzNPMCAJqtLrDWyMvmRfm/W0Pin5GIRa7uq+NNmgiHVdUnrhoVQpGpCi1cxatjHIzlBVAEsdHkSTHqsbX80JzKsJ6D0aB8gjT6D8OuYrsdYZp2fMeEyUFqBEnNQh8a+tK10zdp9GR9tqvNqGysb1PCZAWyrfPZ0viUVsvv038nDrop6UE+pNJMA4UYpgnU5wp3ZtxNwupl5FTFZIAq1QNJhgFXg/vHTEVbPiuK3EzrD34ab1wffKyJIBOYwcYS7evWZSvzsPtqM/PUuPhmoJOoWJovbMlZjpvK722aEpWTQ+wJOznHyHmghqnd1QAJ9TF8W8pmUezWc5Pg7onRiDhgWE8Rk70Zpm/SKDQ6kMrHPYwUP0WsKKneNCVPwus+II4AkE88vQ72WlpuAJjm5dXRcCrg8mqd8CfwvNISG1jj5spDesy8SdcNp6tu9lKD7gA/ENg+lR4izyrpZuxAvQwcPEoEuTTd2mPFq2HWVg9hIdwkGjR+0wVxHXobzdwhoIN4h/CQM=
