language: elixir
elixir:
- 1.3.2
before_install:
- mix local.hex --force
- mix local.rebar --force
- mix do deps.get, deps.compile
script:
- mix test
env:
- TWITTER_CONSUMER_KEY=abc TWITTER_CONSUMER_SECRET=abc
deploy:
  matrix:
  - provider: heroku
  api_key:
    secure: 2cJDvp/FZl9teAJAWjI9/p+s5BsSMjJJP1OmaCLP5zvcROXWh8mMDM19qUS5bAUbDTYwRd3z6CWx3wuF9w3ca3yKuNQ23SVOF/GBTMj123ocxifEcPZM5Vhpy+OhuxEJNxxq+sl+15KPVCQoTLGh8Am9grdaY3OKkhJBnmnIg5K77TnLYE4Ei688ui3mMFl+f3vXs4Z1RKC+laS66jxDU+1QldSCnpeFC8Mapsu0wqz6tyDBHxX/LXoMLSfN3aLYWMKZebL46rHz4414LVPr3LpuMRhYLHtTWN2iVID3Fc/kEwYV0yNNlDUczILjBwIwgic93Dj4ikXUoYIj4JS9YiW3iCr67F6OSS2w+uxZbMtUeAx/hDCFJpKjyMCc44M7y0Trfb1SWhfUzfIaMBywOetzWESwQIR3p8Ju8rtVTjP91otXz1LtJJzCPmHyKGzB8d7WIZznjQb14ShoOTBipVbQiOkh7tv14TKJYWPkx75fu4C7vXm6mUoW09cvEBYvTY/q5sqjWQb80necGBS0ui2r7xL0XyodtqJdW0Tv4inSXOS7TJhvPpTWSbaiAwRKxqLb8sHUgN92UkvHVTp6iYkjJOjREcVA4FW9vrIqlgj801i9GeENgIAV8Dzh/pgCuu0nezn+tnQoGw1Ltj0z/h8dzLRzYYDnC4z7nH6m+RA=
