language: elixir
elixir:
- 1.3.2
before_install:
- mix local.hex --force
- mix local.rebar --force
- mix do deps.get, deps.compile
script:
- mix test
env:
- TWITTER_CONSUMER_KEY=abc TWITTER_CONSUMER_SECRET=abc
deploy:
  provider: heroku
  api_key:
    secure: iuhwBcDbVofYwbbn/GweGFWvAsNFPy6n6hNFvGlPT8JY4MnzxPxRJFlJlmjZ+8VAS4B9r0CG+tDoHHhREgoaqgiJWgg8L0wKjdX0HESR74SsmkPfDSYcD2UI2Hwm+aA0XC9bfyKVOQudYBKP0uVzklrQPmos6Nyf2q8dEpdbQa5/4pqDZPuCKTsky8aYEn1snavrJlDZ46kxsfsCj/sQnA6tbz+/wp511yMBUym5CV7Efdy8rT2dsI6vqrJ/FkTWkFaNDNQs49q0AVoeL23FX6Wwbz1z8HTqvqWPb/Tf/vXwA/gZJwuQHlOQQGqnpxXum0EHCldI36AfuKGd0l+W4qy2PF/uHZ3pQevR26tSgx1IRNO/u1yUW+nkI6RwJYnVpptAcG3MCFSkCDWerKwWbrYVuSZuDQa45aifXhCKFDfw8FFHOitnqhyVxUM9l4Jq0oF8phKyPJsjOtKZ1LTq665HetVnsXZ+afJNy43Ss/9lyomD0juwECSNUFsvDZ29zjc2WBB0Zn13ag3CxDk6GvQ/cAZFrqsS+D3oO9vTKbsVWU5OlLFoZYImM7m+9D/q3GowzUHYv54UU/sj6rDQR5ktxtFUHMpG5gNdc+qn2eRzanEyPFi17xioh9GaWWaHQ+WTV6xjHelfyP3h3fCqaEWRUgqYSZv9yk9j9RCAiUo=
